/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admin/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Страница предстоящих встреч — общий список бронирований всех типов.
         *
         *     `from` и `to` — включительные календарные даты в таймзоне конфига.
         *     Диапазон `from` > `to` не является ошибкой: фильтр вырождается в пустой результат.
         */
        get: operations["listBookings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/event-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listEventTypes"];
        put?: never;
        post: operations["createEventType"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/event-types/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getEventType"];
        put: operations["updateEventType"];
        post?: never;
        /**
         * @description Удалить тип события.
         *     409 — у типа события есть брони, удаление заблокировано.
         */
        delete: operations["deleteEventType"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Создать бронь на выбранный слот.
         *
         *     Сервер не доверяет клиенту и заново проверяет свободность `start`:
         *     400 — malformed тело/поля (проверяет router), 404 — нет типа события,
         *     422 — `start` синтаксически корректен, но не является базовым кандидатом
         *     (вне сетки, окна или рабочих часов),
         *     409 — базовый кандидат корректен, но слот уже занят (в т.ч. гонка гостей);
         *     занятость владельца общая между всеми типами событий.
         *     При успехе `end`, `status: confirmed` и `createdAt` проставляет сервер.
         *     Входной timestamp принимается с любым корректным offset (сравнение как момент
         *     времени); ответные timestamps сериализуются в UTC с `Z`.
         */
        post: operations["createBooking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Витрина видов брони: название, описание, длительность. */
        get: operations["browseEventTypes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-types/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["viewEventType"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-types/{id}/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Свободные слоты для типа события в диапазоне дат.
         *
         *     `from` и `to` — включительные календарные даты, трактуются в таймзоне конфига
         *     (`PublicConfig.timezone`). `from` > `to` — ошибка `400`.
         *     Сервер пересекает [from, to] с окном бронирования (сегодня и следующие 13 дат
         *     в таймзоне конфига) и рабочими часами из конфига, нарезает по длительности
         *     типа события с шагом `slotStepMinutes` и вычитает пересечения с бронями.
         *     Занятость владельца общая между всеми типами событий: любая бронь блокирует
         *     пересекающиеся слоты любого типа. Слоты смежные допустимы: [start, end).
         *     Диапазон, целиком лежащий вне окна бронирования, возвращает `200 []`.
         *
         *     Пример ответа ниже нужен мок-серверу Prism. Даты статичны и со временем
         *     выходят из окна бронирования — это ограничение Prism; stateful и негативные
         *     сценарии покрывает MSW.
         */
        get: operations["listSlots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Готовность процесса. Внешних зависимостей в v1 нет. */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Malformed JSON, отсутствующие или неверные поля, неверные query-параметры
         *     и диапазон `from` > `to` в `listSlots`.
         * @example {
         *       "statusCode": 400,
         *       "code": "bad_request"
         *     }
         */
        BadRequest: {
            /** @enum {string} */
            code: "bad_request";
        };
        /**
         * @description Пустая или состоящая только из пробелов строка.
         *     Позволяет клиенту передать "заглушку" для email/описания:
         *     backend после trim превращает её в отсутствие значения.
         */
        BlankString: string;
        /**
         * @description Бронирование гостя.
         * @example {
         *       "id": "bk_001",
         *       "eventTypeId": "evt_consultation",
         *       "guestName": "Анна Иванова",
         *       "guestEmail": "anna@example.com",
         *       "start": "2026-08-10T09:00:00+03:00",
         *       "end": "2026-08-10T09:30:00+03:00",
         *       "status": "confirmed",
         *       "createdAt": "2026-08-05T10:00:00Z"
         *     }
         */
        Booking: {
            id: string;
            eventTypeId: string;
            guestName: string;
            /** Format: email */
            guestEmail?: string;
            /** Format: date-time */
            start: string;
            /**
             * Format: date-time
             * @description = `start` + `durationMinutes` типа события. Проставляет сервер.
             */
            end: string;
            status: components["schemas"]["BookingStatus"];
            /** Format: date-time */
            createdAt: string;
        };
        /** @description Тело запроса на бронирование. */
        BookingInput: {
            eventTypeId: string;
            /**
             * Format: date-time
             * @description Начало выбранного слота. Должно совпасть с одним из свободных слотов.
             */
            start: string;
            guestName: string;
            /** @description Пустая/whitespace-строка допустима только здесь — backend нормализует её в отсутствие поля. */
            guestEmail?: components["schemas"]["BlankString"] | components["schemas"]["Email"];
        };
        /**
         * @description Статус брони. В v1 — только подтверждённые: отмены/переноса нет.
         * @enum {string}
         */
        BookingStatus: "confirmed";
        /**
         * Format: email
         * @description Корректный email. Сохраняется в исходном регистре, без lowercase.
         */
        Email: string;
        /**
         * @description Тип события, которым управляет владелец.
         * @example {
         *       "id": "evt_consultation",
         *       "title": "Консультация",
         *       "description": "Короткий созвон, чтобы обсудить ваш вопрос.",
         *       "durationMinutes": 30
         *     }
         */
        EventType: {
            /** @description Идентификатор. Генерируется сервером. */
            id: string;
            title: string;
            description?: string;
            /**
             * @description Длительность встречи. В v1 — только два режима.
             * @enum {number}
             */
            durationMinutes: 15 | 30;
        };
        /**
         * @description Нельзя изменить длительность типа события, у которого есть существующие брони.
         *     Название и описание менять можно; `durationMinutes` — нет.
         * @example {
         *       "statusCode": 409,
         *       "code": "event_type_duration_locked"
         *     }
         */
        EventTypeDurationLocked: {
            /** @enum {string} */
            code: "event_type_duration_locked";
        };
        /**
         * @description Нельзя удалить тип события, у которого есть существующие брони.
         * @example {
         *       "statusCode": 409,
         *       "code": "event_type_has_bookings"
         *     }
         */
        EventTypeHasBookings: {
            /** @enum {string} */
            code: "event_type_has_bookings";
        };
        /**
         * @description Тело запроса на создание/изменение типа события.
         *     Без `id` — его проставляет сервер; пользователь задаёт только нейминг.
         */
        EventTypeInput: {
            title: string;
            description?: string;
            /** @enum {number} */
            durationMinutes: 15 | 30;
        };
        /** @description Ответ health check. */
        HealthResponse: {
            /** @enum {string} */
            status: "ok";
        };
        /**
         * @description Неожиданная внутренняя ошибка. Технические детали клиенту не раскрываются.
         * @example {
         *       "statusCode": 500,
         *       "code": "internal_error"
         *     }
         */
        InternalError: {
            /** @enum {string} */
            code: "internal_error";
        };
        /**
         * @description `start` синтаксически корректен, но не является базовым кандидатом:
         *     не бьётся с сеткой слотов, лежит вне окна бронирования или рабочих часов.
         *     Malformed-поля тела запроса — это `400`, а не `422`.
         * @example {
         *       "statusCode": 422,
         *       "code": "invalid_slot"
         *     }
         */
        InvalidSlot: {
            /** @enum {string} */
            code: "invalid_slot";
        };
        /**
         * @example {
         *       "statusCode": 404,
         *       "code": "not_found"
         *     }
         */
        NotFound: {
            /** @enum {string} */
            code: "not_found";
        };
        /**
         * @description Превышен лимит тела запроса (стандартный лимит `express.json()` в 100kb).
         * @example {
         *       "statusCode": 413,
         *       "code": "payload_too_large"
         *     }
         */
        PayloadTooLarge: {
            /** @enum {string} */
            code: "payload_too_large";
        };
        /**
         * @description Публичная часть конфига доступности — нужна фронту для рендера календаря.
         * @example {
         *       "timezone": "Europe/Moscow",
         *       "bookingWindowDays": 14,
         *       "slotStepMinutes": 15,
         *       "workingHours": {
         *         "days": [
         *           1,
         *           2,
         *           3,
         *           4,
         *           5
         *         ],
         *         "start": "09:00",
         *         "end": "18:00"
         *       }
         *     }
         */
        PublicConfig: {
            /** @description Например, "Europe/Moscow". */
            timezone: string;
            /**
             * Format: int32
             * @description Окно бронирования: сегодня и следующие 13 календарных дат в таймзоне конфига.
             */
            bookingWindowDays: number;
            /**
             * Format: int32
             * @description Шаг сетки свободных слотов в минутах, в v1 — 15.
             */
            slotStepMinutes: number;
            workingHours: components["schemas"]["WorkingHours"];
        };
        /**
         * @description Вычисляемый свободный слот (не хранится, только читается гостем).
         * @example {
         *       "start": "2026-08-10T09:00:00+03:00",
         *       "end": "2026-08-10T09:15:00+03:00"
         *     }
         */
        Slot: {
            /**
             * Format: date-time
             * @description Начало слота. Смежные слоты допустимы: [start, end).
             */
            start: string;
            /** Format: date-time */
            end: string;
        };
        /**
         * @description Слот уже занят к моменту брони (в т.ч. гонка двух гостей за один слот).
         * @example {
         *       "statusCode": 409,
         *       "code": "slot_unavailable"
         *     }
         */
        SlotUnavailable: {
            /** @enum {string} */
            code: "slot_unavailable";
        };
        /** @description Рабочие часы владельца — фиксированная часть конфига доступности. */
        WorkingHours: {
            /** @description Дни недели приёма (1 = Пн … 7 = Вс). */
            days: number[];
            /** @description Начало рабочего окна в таймзоне конфига, например "09:00". */
            start: string;
            /** @description Конец рабочего окна в таймзоне конфига, например "18:00". */
            end: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listBookings: {
        parameters: {
            query?: {
                from?: string;
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"][];
                };
            };
            /**
             * @description Malformed JSON, отсутствующие или неверные поля, неверные query-параметры
             *     и диапазон `from` > `to` в `listSlots`.
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BadRequest"];
                };
            };
            /** @description Неожиданная внутренняя ошибка. Технические детали клиенту не раскрываются. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalError"];
                };
            };
        };
    };
    listEventTypes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"][];
                };
            };
            /** @description Неожиданная внутренняя ошибка. Технические детали клиенту не раскрываются. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalError"];
                };
            };
        };
    };
    createEventType: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventTypeInput"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /**
             * @description Malformed JSON, отсутствующие или неверные поля, неверные query-параметры
             *     и диапазон `from` > `to` в `listSlots`.
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BadRequest"];
                };
            };
            /** @description Неожиданная внутренняя ошибка. Технические детали клиенту не раскрываются. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalError"];
                };
            };
        };
    };
    getEventType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFound"];
                };
            };
            /** @description Неожиданная внутренняя ошибка. Технические детали клиенту не раскрываются. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalError"];
                };
            };
        };
    };
    updateEventType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventTypeInput"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /**
             * @description Malformed JSON, отсутствующие или неверные поля, неверные query-параметры
             *     и диапазон `from` > `to` в `listSlots`.
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BadRequest"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFound"];
                };
            };
            /**
             * @description Нельзя изменить длительность типа события, у которого есть существующие брони.
             *     Название и описание менять можно; `durationMinutes` — нет.
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventTypeDurationLocked"];
                };
            };
            /** @description Неожиданная внутренняя ошибка. Технические детали клиенту не раскрываются. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalError"];
                };
            };
        };
    };
    deleteEventType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description There is no content to send for this request, but the headers may be useful. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFound"];
                };
            };
            /** @description Нельзя удалить тип события, у которого есть существующие брони. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventTypeHasBookings"];
                };
            };
            /** @description Неожиданная внутренняя ошибка. Технические детали клиенту не раскрываются. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalError"];
                };
            };
        };
    };
    createBooking: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookingInput"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            /**
             * @description Malformed JSON, отсутствующие или неверные поля, неверные query-параметры
             *     и диапазон `from` > `to` в `listSlots`.
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BadRequest"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFound"];
                };
            };
            /** @description Слот уже занят к моменту брони (в т.ч. гонка двух гостей за один слот). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlotUnavailable"];
                };
            };
            /**
             * @description `start` синтаксически корректен, но не является базовым кандидатом:
             *     не бьётся с сеткой слотов, лежит вне окна бронирования или рабочих часов.
             *     Malformed-поля тела запроса — это `400`, а не `422`.
             */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvalidSlot"];
                };
            };
            /** @description Неожиданная внутренняя ошибка. Технические детали клиенту не раскрываются. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalError"];
                };
            };
        };
    };
    getConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicConfig"];
                };
            };
            /** @description Неожиданная внутренняя ошибка. Технические детали клиенту не раскрываются. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalError"];
                };
            };
        };
    };
    browseEventTypes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"][];
                };
            };
            /** @description Неожиданная внутренняя ошибка. Технические детали клиенту не раскрываются. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalError"];
                };
            };
        };
    };
    viewEventType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFound"];
                };
            };
            /** @description Неожиданная внутренняя ошибка. Технические детали клиенту не раскрываются. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalError"];
                };
            };
        };
    };
    listSlots: {
        parameters: {
            query: {
                from: string;
                to: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example [
                     *       {
                     *         "start": "2026-08-10T09:00:00+03:00",
                     *         "end": "2026-08-10T09:15:00+03:00"
                     *       },
                     *       {
                     *         "start": "2026-08-10T09:15:00+03:00",
                     *         "end": "2026-08-10T09:30:00+03:00"
                     *       },
                     *       {
                     *         "start": "2026-08-10T10:00:00+03:00",
                     *         "end": "2026-08-10T10:15:00+03:00"
                     *       },
                     *       {
                     *         "start": "2026-08-11T09:00:00+03:00",
                     *         "end": "2026-08-11T09:15:00+03:00"
                     *       },
                     *       {
                     *         "start": "2026-08-11T11:00:00+03:00",
                     *         "end": "2026-08-11T11:15:00+03:00"
                     *       }
                     *     ]
                     */
                    "application/json": components["schemas"]["Slot"][];
                };
            };
            /**
             * @description Malformed JSON, отсутствующие или неверные поля, неверные query-параметры
             *     и диапазон `from` > `to` в `listSlots`.
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BadRequest"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFound"];
                };
            };
            /** @description Неожиданная внутренняя ошибка. Технические детали клиенту не раскрываются. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalError"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Неожиданная внутренняя ошибка. Технические детали клиенту не раскрываются. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalError"];
                };
            };
        };
    };
}
